Repository wespot-bff/WeSpot-Android, pull requests merged in 2024-06, with the labels that each got.

#6 Chore/jaino/#5
  .github/workflows/opened-pr-notification.yml
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/com/bff/wespot/plugin/AndroidApplicationPlugin.kt
  build-logic/convention/src/main/kotlin/com/bff/wespot/plugin/AndroidFeaturePlugin.kt
  build-logic/convention/src/main/kotlin/com/bff/wespot/plugin/AndroidLibraryPlugin.kt
  build-logic/convention/src/main/kotlin/com/bff/wespot/plugin/AndroidLintPlugin.kt
  build-logic/convention/src/main/kotlin/com/bff/wespot/plugin/JvmLibraryPlugin.kt
  build-logic/convention/src/main/kotlin/com/bff/wespot/plugin/configure/AndroidLint.kt
  build-logic/settings.gradle.kts
  build.gradle.kts
  config/detekt.yml
  gradle/libs.versions.toml
  script/hookScript
  script/setupLint.sh
Labels: 🍻제이콥🍻, 🌟머지 해주세요🌟, 🧹허드렛일🧹, 📄문서📄

#8 #3: Theme추가및 추가 세팅
  .gitignore
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/com/bff/wespot/plugin/AndroidComposePlugin.kt
  build-logic/convention/src/main/kotlin/com/bff/wespot/plugin/AndroidFeaturePlugin.kt
  config/detekt.yml
  core/common/src/main/kotlin/com/bff/wespot/common/empty
  core/ui/build.gradle.kts
  core/ui/src/main/kotlin/com/bff/wespot/ui/empty
  designsystem/build.gradle.kts
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/empty
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/theme/Color.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/theme/Shape.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/theme/Theme.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/theme/Type.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/util/Extension.kt
  designsystem/src/main/res/font/pretendard_bold.ttf
  designsystem/src/main/res/font/pretendard_m.ttf
  designsystem/src/main/res/font/pretendard_r.ttf
  designsystem/src/main/res/font/pretendard_semibold.ttf
  feature/auth/build.gradle.kts
  gradle/libs.versions.toml
Labels: 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟, 🧹허드렛일🧹

#11 #10 : Jira 연동 Github Actions 구현
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
Labels: 🍻제이콥🍻, 🌟머지 해주세요🌟, 🧹허드렛일🧹
