Repository wespot-bff/WeSpot-Android, pull requests merged in 2024-10, with the labels that each got.

#173 #171 : 쪽지 시간 KST 설정 및 백스택 처리해요
  .github/workflows/submitted-pr-review-notification.yml
  app/src/main/kotlin/com/bff/wespot/CommonNavGraphNavigator.kt
  core/network/src/main/kotlin/com/bff/wespot/network/extensions/HttpClientExtensions.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/model/TimePeriod.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/MessageEditScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/SendViewModel.kt
Labels: 🍻제이콥🍻, 🔨픽스🔨

#174 [FEAT]#172 : CIO -> okHttp로 마이그레이션 진행
  data/src/main/kotlin/com/bff/wespot/data/di/ClientModule.kt
  gradle/libs.versions.toml
Labels: 🍻제이콥🍻, 🔨픽스🔨

#161 #151 : 서버로부터 받은 예외 뷰 타입 처리 구현
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  app/src/main/kotlin/com/bff/wespot/PushNotificationService.kt
  app/src/main/kotlin/com/bff/wespot/application/WeSpotApplication.kt
  app/src/main/kotlin/com/bff/wespot/di/ConfigModule.kt
  core/analytics/src/main/java/com/bff/wespot/analytic/DebugAnalyicsHelper.kt
  core/model/src/main/kotlin/com/bff/wespot/model/exception/NetworkException.kt
  core/model/src/main/kotlin/com/bff/wespot/model/exception/NetworkExceptionViewType.kt
  core/ui/src/main/kotlin/com/bff/wespot/base/BaseViewModel.kt
  core/ui/src/main/kotlin/com/bff/wespot/di/CoroutineModule.kt
  core/ui/src/main/kotlin/com/bff/wespot/model/SideEffect.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/SideEffectHandler.kt
  core/ui/src/main/kotlin/com/bff/wespot/util/SideEffectFlow.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/AuthActivity.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/AuthScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/CompleteScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/viewmodel/AuthViewModel.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/edit/CharacterEditScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/edit/ProfileEditScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/setting/BlockListScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/setting/NotificationSettingScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/setting/RevokeConfirmScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/viewmodel/EntireEditViewModel.kt
  feature/entire/src/main/java/com/bff/wespot/entire/viewmodel/EntireViewModel.kt
  feature/entire/src/main/java/com/bff/wespot/entire/viewmodel/NotificationSettingViewModel.kt
  feature/entire/src/main/res/values/strings.xml
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageHomeScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/ReservedMessageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/MessageEditScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/MessageWriteScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/ReceiverSelectionScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/storage/MessageStorageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/MessageViewModel.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/SendViewModel.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/StorageViewModel.kt
  feature/message/src/main/res/values/strings.xml
  feature/notification/src/main/kotlin/com/bff/wespot/notification/screen/NotificationScreen.kt
  feature/notification/src/main/kotlin/com/bff/wespot/notification/viewmodel/NotificationViewModel.kt
  feature/notification/src/main/res/values/strings.xml
  feature/vote/src/main/java/com/bff/wespot/vote/screen/CharacterSettingScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/IndividualVoteScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/IntroductionScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteHomeScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteResultScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteStorageScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VotingScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/CharacterSettingViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/IndividualViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/IntroductionViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VoteHomeViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VoteResultViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VoteStorageViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VotingViewModel.kt
Labels: 🌱기능🌱, 🍻제이콥🍻

#176 #175 : 푸시 알림 클릭시 흰 화면으로 랜딩하는 이슈 수정해요
  app/src/main/kotlin/com/bff/wespot/PushNotificationService.kt
  app/src/main/kotlin/com/bff/wespot/splash/SplashActivity.kt
  app/src/main/res/drawable-xhdpi/ic_notification.png
  app/src/main/res/drawable-xxhdpi/ic_notification.png
  app/src/main/res/drawable-xxxhdpi/ic_notification.png
  app/src/main/res/mipmap-anydpi-v26/ic_notification.png
Labels: 🍻제이콥🍻, 🔨픽스🔨

#178 버전 업데이트
  gradle/libs.versions.toml
Labels: 🌱기능🌱, 🍩브라우니🍩, 🌟머지 해주세요🌟

#183 #182 : 쪽지 진입시 시간대에 맞는 로띠 노출되도록 수정해요
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/MessageViewModel.kt
Labels: 🍻제이콥🍻, 🔨픽스🔨

#180 #179 : 알림 아이콘 충돌 해결해요 + 리드미 업데이트
  README.md
  app/src/main/kotlin/com/bff/wespot/PushNotificationService.kt
  app/src/main/kotlin/com/bff/wespot/splash/SplashActivity.kt
  app/src/main/res/drawable-xhdpi/ic_push_notification.png
  app/src/main/res/drawable-xxhdpi/ic_push_notification.png
  app/src/main/res/drawable-xxxhdpi/ic_push_notification.png
  build.gradle.kts
  gradle/libs.versions.toml
  module_graph.svg
Labels: 🍻제이콥🍻, 🔨픽스🔨

#185 #184 : 타이머 시작시, 쪽지 상태 불러오는 코드 추가해요
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/MessageViewModel.kt
Labels: 🍻제이콥🍻, 🔨픽스🔨

#186 #181: 카카오톡 로그인 뒤로갈시 튕기는 버그 수정
  core/ui/src/main/kotlin/com/bff/wespot/ui/util/KakaoLoginManager.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/AuthScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/viewmodel/EntireViewModel.kt
Labels: 🍩브라우니🍩, 🔨픽스🔨
