Repository wespot-bff/WeSpot-Android, pull requests merged in 2024-07, with the labels that each got.

#19 #9: 디자인 시스템 컴포넌트 추가 - 1
  build-logic/convention/src/main/kotlin/com/bff/wespot/plugin/AndroidLibraryPlugin.kt
  core/common/src/main/kotlin/com/bff/wespot/common/StringSet.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/banner/WSBanner.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/button/WSButton.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/button/WSOutlineButton.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/button/WSTextButtonType.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/input/WsTextField.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/theme/Shape.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/theme/Theme.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/util/CustomPreview.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/empty
Labels: 🌱기능🌱, 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟, ✏️수정 요청✏️

#24 #13 : 쪽지 전용 컴포넌트 구현
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/com/bff/wespot/plugin/AndroidKtLintPlugin.kt
  build-logic/convention/src/main/kotlin/com/bff/wespot/plugin/configure/AndroidLint.kt
  core/ui/build.gradle.kts
  designsystem/build.gradle.kts
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/banner/WSBanner.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/button/WSButton.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/button/WSTextButtonType.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/header/WSTopBar.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/indicator/WSToast.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/input/WsTextField.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/list/WSLetterItem.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/modal/WSDialog.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/toggle/WSSwitch.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/util/CustomPreview.kt
  designsystem/src/main/res/drawable/check.xml
  designsystem/src/main/res/drawable/closed_letter.png
  designsystem/src/main/res/drawable/error.xml
  designsystem/src/main/res/drawable/opened_letter.png
  designsystem/src/main/res/drawable/option.xml
  designsystem/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥, 📄문서📄

#25 #21: 편집 화면 전까지 회원가입 화면 추가
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  core/model/src/main/kotlin/com/bff/wespot/model/SchoolItem.kt
  core/model/src/main/kotlin/com/bff/wespot/model/empty
  core/ui/src/main/kotlin/com/bff/wespot/ui/SchoolListItem.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/WSBottomSheet.kt
  core/ui/src/main/res/drawable/exclude.xml
  core/ui/src/main/res/drawable/female_student.png
  core/ui/src/main/res/drawable/male_student.png
  core/ui/src/main/res/values/string.xml
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/ClassScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/GenderScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/GradeScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/NameScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/SchoolScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/state/AuthAction.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/state/AuthSideEffect.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/state/AuthUiState.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/viewmodel/AuthViewModel.kt
  feature/auth/src/main/res/values/string.xml
Labels: 🌱기능🌱, 🍩브라우니🍩, 🌟머지 해주세요🌟

#26 #21: 회원가입 화면 완성
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/SchoolListItem.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/WSBottomSheet.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/button/WSButton.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/theme/Color.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/theme/Shape.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/theme/Theme.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/theme/Type.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/util/Extension.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/ClassScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/CompleteScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/EditScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/GenderScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/GradeScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/NameScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/SchoolScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/viewmodel/AuthViewModel.kt
  feature/auth/src/main/res/drawable/profile.xml
  feature/auth/src/main/res/values/string.xml
Labels: 🌱기능🌱, 🍩브라우니🍩, 🌟머지 해주세요🌟

#27 #14 : 쪽지 홈 API 구현 및 Ktor 네트워크 설정 작업
  .github/workflows/opened-pr-notification.yml
  .github/workflows/submitted-pr-review-notification.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/bff/wespot/application/WeSpotApplication.kt
  build-logic/convention/src/main/kotlin/com/bff/wespot/plugin/configure/AndroidLint.kt
  build.gradle.kts
  core/model/src/main/kotlin/com/bff/wespot/model/message/request/MessageType.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/request/SentMessage.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/Message.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/MessageList.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/MessageStatus.kt
  core/network/.gitignore
  core/network/build.gradle.kts
  core/network/proguard-rules.pro
  core/network/src/main/kotlin/com/bff/wespot/network/di/ClientModule.kt
  core/network/src/main/kotlin/com/bff/wespot/network/di/NetworkModule.kt
  core/network/src/main/kotlin/com/bff/wespot/network/extensions/HttpClientExtensions.kt
  core/network/src/main/kotlin/com/bff/wespot/network/model/exception/NetworkException.kt
  core/network/src/main/kotlin/com/bff/wespot/network/model/message/request/MessageTypeDto.kt
  core/network/src/main/kotlin/com/bff/wespot/network/model/message/request/SentMessageDto.kt
  core/network/src/main/kotlin/com/bff/wespot/network/model/message/response/MessageDto.kt
  core/network/src/main/kotlin/com/bff/wespot/network/model/message/response/MessageIdDto.kt
  core/network/src/main/kotlin/com/bff/wespot/network/model/message/response/MessageListDto.kt
  core/network/src/main/kotlin/com/bff/wespot/network/model/message/response/MessageStatusDto.kt
  core/network/src/main/kotlin/com/bff/wespot/network/source/message/MessageDataSource.kt
  core/network/src/main/kotlin/com/bff/wespot/network/source/message/MessageDataSourceImpl.kt
  core/network/src/test/kotlin/com/bff/wespot/network/ExampleUnitTest.kt
  data/build.gradle.kts
  data/src/main/kotlin/com/bff/wespot/data/di/DataModule.kt
  data/src/main/kotlin/com/bff/wespot/data/empty
  data/src/main/kotlin/com/bff/wespot/data/mapper/message/MessageMapper.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/message/MessageRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/kotlin/com/bff/wespot/domain/empty
  domain/src/main/kotlin/com/bff/wespot/domain/repository/message/MessageRepository.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟, 📄문서📄

#33 #7: 카카오톡 로그인 로직 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/bff/wespot/application/WeSpotApplication.kt
  core/model/src/main/kotlin/com/bff/wespot/model/auth/KakaoAuthToken.kt
  data/build.gradle.kts
  data/src/main/kotlin/com/bff/wespot/data/di/DataModule.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/auth/KakaoLoginManagerImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/auth/KakaoLoginManager.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/usecase/KakaoLoginUseCase.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/kotlin/com/bff/wespot/auth/AuthScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/viewmodel/AuthViewModel.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 🌱기능🌱, 🍩브라우니🍩, 🌟머지 해주세요🌟

#34 #29: AuthActivity를 만들어 회원가입을 진행해요
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  app/src/main/kotlin/com/bff/wespot/NavigatorImpl.kt
  app/src/main/kotlin/com/bff/wespot/di/NavigationModule.kt
  core/navigation/.gitignore
  core/navigation/build.gradle.kts
  core/navigation/consumer-rules.pro
  core/navigation/proguard-rules.pro
  core/navigation/src/main/AndroidManifest.xml
  core/navigation/src/main/java/com/danggeun/navigation/Navigator.kt
  core/navigation/src/main/java/com/danggeun/navigation/util/Extension.kt
  domain/src/main/kotlin/com/bff/wespot/domain/usecase/KakaoLoginUseCase.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/AuthActivity.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/ClassScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/EditScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/GenderScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/GradeScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/NameScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/SchoolScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/state/AuthAction.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/state/AuthSideEffect.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/viewmodel/AuthViewModel.kt
  settings.gradle.kts
Labels: 🍩브라우니🍩, 🌟머지 해주세요🌟, 🔧리팩터링🔧

#35 #30: 회원가입 서버와 연동을 해요
  app/build.gradle.kts
  app/src/main/kotlin/com/bff/wespot/NavigatorImpl.kt
  app/src/main/kotlin/com/bff/wespot/di/NavigationModule.kt
  core/common/src/main/kotlin/com/danggeun/common/di/CoroutineModule.kt
  core/model/src/main/kotlin/com/bff/wespot/model/SchoolItem.kt
  core/model/src/main/kotlin/com/bff/wespot/model/auth/request/KakaoAuthToken.kt
  core/model/src/main/kotlin/com/bff/wespot/model/auth/request/SignUp.kt
  core/model/src/main/kotlin/com/bff/wespot/model/auth/response/AuthToken.kt
  core/model/src/main/kotlin/com/bff/wespot/model/auth/response/Consents.kt
  core/model/src/main/kotlin/com/bff/wespot/model/auth/response/School.kt
  core/model/src/main/kotlin/com/bff/wespot/model/auth/response/SignUpToken.kt
  core/model/src/main/kotlin/com/bff/wespot/model/constants/LoginState.kt
  core/navigation/src/main/java/com/wespot/navigation/Navigator.kt
  core/navigation/src/main/java/com/wespot/navigation/util/Extension.kt
  core/network/src/main/kotlin/com/bff/wespot/network/di/ClientModule.kt
  core/network/src/main/kotlin/com/bff/wespot/network/di/NetworkModule.kt
  core/network/src/main/kotlin/com/bff/wespot/network/extensions/HttpClientExtensions.kt
  core/network/src/main/kotlin/com/bff/wespot/network/model/auth/request/ConsentsDto.kt
  core/network/src/main/kotlin/com/bff/wespot/network/model/auth/request/KakaoAuthTokenDto.kt
  core/network/src/main/kotlin/com/bff/wespot/network/model/auth/request/SignUpDto.kt
  core/network/src/main/kotlin/com/bff/wespot/network/model/auth/response/AuthTokenDto.kt
  core/network/src/main/kotlin/com/bff/wespot/network/model/auth/response/SchoolDto.kt
  core/network/src/main/kotlin/com/bff/wespot/network/model/auth/response/SchoolListDto.kt
  core/network/src/main/kotlin/com/bff/wespot/network/model/auth/response/SignUpTokenDto.kt
  core/network/src/main/kotlin/com/bff/wespot/network/source/auth/AuthDataSource.kt
  core/network/src/main/kotlin/com/bff/wespot/network/source/auth/AuthDataSourceImpl.kt
  data/build.gradle.kts
  data/src/main/kotlin/com/bff/wespot/data/di/DataModule.kt
  data/src/main/kotlin/com/bff/wespot/data/local/WeSpotDataStore.kt
  data/src/main/kotlin/com/bff/wespot/data/local/WeSpotDataStoreImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/mapper/auth/AuthMapper.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/DataStoreRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/auth/AuthRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/auth/KakaoLoginManagerImpl.kt
  domain/build.gradle.kts
  domain/src/main/kotlin/com/bff/wespot/domain/repository/DataStoreRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/auth/AuthRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/auth/KakaoLoginManager.kt
  domain/src/main/kotlin/com/bff/wespot/domain/usecase/AutoLoginUseCase.kt
  domain/src/main/kotlin/com/bff/wespot/domain/usecase/KakaoLoginUseCase.kt
  domain/src/main/kotlin/com/bff/wespot/domain/util/DataStoreKey.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/kotlin/com/bff/wespot/auth/AuthActivity.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/AuthScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/AuthScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/CompleteScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/EditScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/SchoolScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/state/AuthAction.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/state/AuthSideEffect.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/state/AuthUiState.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/viewmodel/AuthViewModel.kt
  feature/auth/src/main/res/drawable/kakao.xml
  feature/auth/src/main/res/values/string.xml
  gradle/libs.versions.toml
Labels: 🌱기능🌱, 🍩브라우니🍩, 🌟머지 해주세요🌟

#36 #15 : 쪽지 홈 화면 구현
  app/build.gradle.kts
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/Message.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/MessageList.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/MessageStatus.kt
  core/network/src/main/kotlin/com/bff/wespot/network/extensions/DateTimeExtensions.kt
  core/network/src/main/kotlin/com/bff/wespot/network/model/message/response/MessageDto.kt
  core/ui/build.gradle.kts
  core/ui/src/main/kotlin/com/bff/wespot/ui/WSHomeTabRow.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/WSHomeTopBar.kt
  core/ui/src/main/res/drawable/logo.png
  core/ui/src/main/res/drawable/notification.xml
  core/ui/src/main/res/values/string.xml
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/banner/WSBanner.kt
  feature/message/.gitignore
  feature/message/build.gradle.kts
  feature/message/consumer-rules.pro
  feature/message/proguard-rules.pro
  feature/message/src/androidTest/java/com/bff/wespot/message/ExampleInstrumentedTest.kt
  feature/message/src/main/AndroidManifest.xml
  feature/message/src/main/kotlin/com/bff/wespot/message/model/TimePeriod.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageAction.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageSideEffect.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageUiState.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/MessageViewModel.kt
  feature/message/src/main/res/drawable/home_message.png
  feature/message/src/main/res/drawable/home_message_dawn.png
  feature/message/src/main/res/drawable/home_message_night.png
  feature/message/src/main/res/drawable/received_message.png
  feature/message/src/main/res/drawable/reserved_message.png
  feature/message/src/main/res/drawable/timer.xml
  feature/message/src/main/res/values/strings.xml
  feature/message/src/test/java/com/bff/wespot/message/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#47 #16 : 쪽지 전달 기능 구현
  core/common/src/main/kotlin/com/bff/wespot/common/di/extensions/ResultExtensions.kt
  core/model/build.gradle.kts
  core/model/src/main/kotlin/com/bff/wespot/model/exception/NetworkException.kt
  core/model/src/main/kotlin/com/bff/wespot/model/user/response/Profile.kt
  core/model/src/main/kotlin/com/bff/wespot/model/user/response/ProfileCharacter.kt
  core/model/src/main/kotlin/com/bff/wespot/model/user/response/User.kt
  core/network/src/main/kotlin/com/bff/wespot/network/extensions/HttpClientExtensions.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/di/DataRemoteModule.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/user/response/ProfileCharacterDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/user/response/ProfileDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/user/response/UserDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/user/response/UserListDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/user/UserDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/user/UserDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/di/DataModule.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/user/UserRepositoryImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/user/UserRepository.kt
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#46 #38: 투표 화면 + 전체 탭 추가해요
  app/build.gradle.kts
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/BottomBarDestinations.kt
  app/src/main/kotlin/com/bff/wespot/CommonNavGraphNavigator.kt
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  build-logic/convention/src/main/kotlin/com/bff/wespot/plugin/AndroidFeaturePlugin.kt
  core/common/src/main/kotlin/com/bff/wespot/common/util/DateTimeConverter.kt
  core/navigation/build.gradle.kts
  core/ui/src/main/kotlin/com/bff/wespot/util/LifecycleUtil.kt
  core/ui/src/main/res/drawable/send.xml
  data-local/.gitignore
  data-local/build.gradle.kts
  data-local/consumer-rules.pro
  data-local/proguard-rules.pro
  data-local/src/main/AndroidManifest.xml
  data-local/src/main/java/com/bff/wespot/data/local/di/DataModule.kt
  data-local/src/main/java/com/bff/wespot/data/local/source/WeSpotDataStore.kt
  data-local/src/main/java/com/bff/wespot/data/local/source/WeSpotDataStoreImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/di/DataRemoteModule.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/vote/VoteDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/vote/VoteDataSourceImpl.kt
  data/build.gradle.kts
  data/src/main/kotlin/com/bff/wespot/data/di/DataModule.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/DataStoreRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/auth/AuthRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/auth/KakaoLoginManagerImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/vote/VoteRepositoryImpl.kt
  designsystem/src/main/res/drawable/entire.xml
  designsystem/src/main/res/drawable/message.xml
  designsystem/src/main/res/drawable/vote_tab.xml
  designsystem/src/main/res/values/strings.xml
  domain/src/main/kotlin/com/bff/wespot/domain/repository/vote/VoteRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/usecase/AutoLoginUseCase.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/kotlin/com/bff/wespot/auth/AuthActivity.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/viewmodel/AuthViewModel.kt
  feature/entire/.gitignore
  feature/entire/build.gradle.kts
  feature/entire/consumer-rules.pro
  feature/entire/proguard-rules.pro
  feature/entire/src/main/AndroidManifest.xml
  feature/entire/src/main/java/com/bff/wespot/entire/screen/EntireScreen.kt
  feature/message/build.gradle.kts
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageScreen.kt
  feature/message/src/main/res/values/strings.xml
  feature/vote/.gitignore
  feature/vote/build.gradle.kts
  feature/vote/consumer-rules.pro
  feature/vote/proguard-rules.pro
  feature/vote/src/main/AndroidManifest.xml
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteHomeScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VotingScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/VoteAction.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/VoteSideEffect.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/VoteUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VoteHomeViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VotingViewModel.kt
  feature/vote/src/main/res/drawable/vote.png
  feature/vote/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: 🌱기능🌱, 🍩브라우니🍩, 🔨픽스🔨, 🌟머지 해주세요🌟

#51 #48: 투표 진행후 결과 화면 작업
  app/src/main/kotlin/com/bff/wespot/CommonNavGraphNavigator.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/request/VoteResultUpload.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/request/VoteResults.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/request/VoteResultsUpload.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/VoteResults.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/DotIndicators.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/MultiLineText.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/WSCarousel.kt
  core/ui/src/main/kotlin/com/bff/wespot/util/ModifierUtil.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/request/VoteResultUploadDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/request/VoteResultsDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/request/VoteResultsUploadDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/VoteResultsDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/vote/VoteDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/vote/VoteDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/mapper/vote/VoteMapper.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/vote/VoteRepositoryImpl.kt
  designsystem/src/main/res/drawable/insta.xml
  domain/src/main/kotlin/com/bff/wespot/domain/repository/vote/VoteRepository.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteResultScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/result/ResultAction.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/result/ResultUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/voting/VotingUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VoteResultViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VotingViewModel.kt
  feature/vote/src/main/res/drawable/empty_vote.png
  feature/vote/src/main/res/drawable/first.png
  feature/vote/src/main/res/drawable/second.png
  feature/vote/src/main/res/drawable/third.png
  feature/vote/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#56 #40 : 받은 쪽지 조회 기능 구현
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/Message.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/MessageList.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/MessageStatus.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/WSHomeChipGroup.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/response/MessageDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/response/MessageListDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/response/MessageStatusDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/message/MessageRepositoryImpl.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/list/WSMessageItem.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/message/MessageRepository.kt
  feature/message/build.gradle.kts
  feature/message/src/main/kotlin/com/bff/wespot/message/common/Constants.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/common/TimeExtensions.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/component/ReservedMessageBanner.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageHomeScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageStorageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/ReceiverSelectionScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageAction.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageUiState.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/MessageViewModel.kt
  feature/message/src/main/res/drawable/close.xml
  feature/message/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#54 #52: 카드 투표 결과 화면 작업
  app/src/main/kotlin/com/bff/wespot/CommonNavGraphNavigator.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/WSCarousel.kt
  core/ui/src/main/kotlin/com/bff/wespot/util/ModifierUtil.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/di/ClientModule.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/vote/VoteDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/vote/VoteDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/vote/VoteRepositoryImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/vote/VoteRepository.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteHomeScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteResultScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VotingScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/home/VoteAction.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/home/VoteUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/result/ResultUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/ui/EmptyResultScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/ui/VoteCard.kt
  feature/vote/src/main/java/com/bff/wespot/vote/ui/VoteChip.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VoteHomeViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VoteResultViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VotingViewModel.kt
  feature/vote/src/main/res/drawable/first_empty.png
  feature/vote/src/main/res/drawable/vote_background.png
  feature/vote/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🍩브라우니🍩, 🌟머지 해주세요🌟

#57 #43, #44 : 쪽지 신고/차단/삭제 기능 구현
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/Message.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/di/DataRemoteModule.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/extensions/DateTimeExtensions.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/response/MessageDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageStorageDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageStorageDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/di/DataModule.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/message/MessageRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/message/MessageStorageRepositoryImpl.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/indicator/WSHomeTabRow.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/input/WsTextField.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/message/MessageRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/message/MessageStorageRepository.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/model/MessageOptionType.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageStorageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/MessageWriteScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/ReceiverSelectionScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageAction.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageSideEffect.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageUiState.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/MessageViewModel.kt
  feature/message/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#58 #41 : 보낸 쪽지 보관함 기능 구현
  config/detekt.yml
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/Message.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/response/MessageDto.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/indicator/WSHomeTabRow.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/list/WSMessageItem.kt
  designsystem/src/main/res/drawable/invalid_message.png
  designsystem/src/main/res/drawable/warning.png
  designsystem/src/main/res/values/strings.xml
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageStorageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageAction.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/MessageViewModel.kt
  feature/message/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#59 #42 : 예약된 쪽지 리스트 구현 및 보낸 쪽지 수정
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/CommonNavGraphNavigator.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/request/SentMessage.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/Message.kt
  core/model/src/main/kotlin/com/bff/wespot/model/user/response/Profile.kt
  core/model/src/main/kotlin/com/bff/wespot/model/user/response/User.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/di/ClientModule.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/request/SentMessageDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/response/MessageDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/response/ReservedMessageListDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/user/response/UserDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageStorageDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageStorageDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/user/UserDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/user/UserDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/mapper/message/MessageMapper.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/message/MessageRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/message/MessageStorageRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/user/UserRepositoryImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/message/MessageRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/message/MessageStorageRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/user/UserRepository.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageHomeScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageStorageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/ReservedMessageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/MessageEditScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/MessageWriteScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/ReceiverSelectionScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageAction.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageUiState.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/send/SendAction.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/send/SendSideEffect.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/send/SendUiState.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/MessageViewModel.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/SendViewModel.kt
  feature/message/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟
