Repository wespot-bff/WeSpot-Android, pull requests merged in 2024-11, with the labels that each got.

#189 #188: 라이브러리 버전 업데이트
  core/ui/build.gradle.kts
  core/ui/src/main/kotlin/com/bff/wespot/ui/component/AutoSizeText.kt
  designsystem/build.gradle.kts
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/indicator/WSHomeTabRow.kt
  gradle/libs.versions.toml
Labels: 🌱기능🌱, 🍩브라우니🍩

#192 #190 : UX 라이팅 수정해요
  README.md
  app/src/main/kotlin/com/bff/wespot/BottomBarDestinations.kt
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  core/model/src/main/kotlin/com/bff/wespot/model/notification/NotificationType.kt
  core/model/src/main/kotlin/com/bff/wespot/model/user/response/Profile.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/banner/WSBanner.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/AuthScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/ClassScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/SchoolScreen.kt
  feature/auth/src/main/res/values/string.xml
  feature/auth/src/main/res/values/strings.xml
  feature/entire/src/main/java/com/bff/wespot/entire/screen/edit/ProfileEditScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/setting/NotificationSettingScreen.kt
  feature/entire/src/main/res/values/strings.xml
  feature/message/src/main/kotlin/com/bff/wespot/message/model/TimePeriod.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageHomeScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/ReservedMessageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/ReceiverSelectionScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/storage/MessageStorageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageAction.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageUiState.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/send/SendUiState.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/MessageViewModel.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/SendViewModel.kt
  feature/message/src/main/res/values/strings.xml
  feature/notification/src/main/kotlin/com/bff/wespot/notification/screen/NotificationScreen.kt
  feature/notification/src/main/res/drawable/ic_message_notification.xml
  feature/notification/src/main/res/drawable/ic_vote_notification.xml
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteHomeScreen.kt
  feature/vote/src/main/res/values/strings.xml
Labels: 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥, 🧹허드렛일🧹

#199 #191: 이미지 업로드 화면 추가해요
  core/ui/src/main/res/values/strings.xml
  feature/auth/build.gradle.kts
  feature/auth/src/main/kotlin/com/bff/wespot/auth/AuthActivity.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/EditScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/ImageScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/NameScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/state/AuthAction.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/state/AuthSideEffect.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/state/AuthUiState.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/viewmodel/AuthViewModel.kt
  feature/auth/src/main/res/drawable/default_character.png
  feature/auth/src/main/res/drawable/gallery.png
  feature/auth/src/main/res/values/strings.xml
  feature/entire/src/main/java/com/bff/wespot/entire/screen/edit/ProfileEditScreen.kt
  feature/entire/src/main/res/values/strings.xml
  feature/vote/src/main/java/com/bff/wespot/vote/ui/VoteCard.kt
Labels: 🌱기능🌱, 🍩브라우니🍩, 🌟머지 해주세요🌟

#203 #202: 프로필 이미지 수정 추가
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/CommonNavGraphNavigator.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/user/UserDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/user/UserDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/user/ProfileRepositoryImpl.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/modal/WSDialog.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/user/ProfileRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/usecase/UpdateProfileCharacterUseCase.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/edit/CharacterEditScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/edit/ProfileEditScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/state/edit/EntireEditAction.kt
  feature/entire/src/main/java/com/bff/wespot/entire/state/edit/EntireEditUiState.kt
  feature/entire/src/main/java/com/bff/wespot/entire/viewmodel/EntireEditViewModel.kt
  feature/entire/src/main/res/values/strings.xml
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteHomeScreen.kt
Labels: 🌱기능🌱, 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥

#206 #204 : 예약된 쪽지 수정화면 수정해요
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/MessageEditScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/send/SendAction.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/SendViewModel.kt
Labels: 🍻제이콥🍻, 🧹허드렛일🧹

#209 #201: 안쓰는 로직 삭제해요
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/CommonNavGraphNavigator.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/component/CharacterScreen.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/component/IntroductionScreen.kt
  core/ui/src/main/res/values/strings.xml
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/CommonDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/CommonDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/CommonRepositoryImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/CommonRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/util/DataStoreKey.kt
  feature/entire/src/main/java/com/bff/wespot/entire/state/edit/EntireEditAction.kt
  feature/entire/src/main/java/com/bff/wespot/entire/viewmodel/EntireEditViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/CharacterSettingScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/IntroductionScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteHomeScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/home/VoteAction.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/home/VoteUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/profile/ProfileAction.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/profile/ProfileSideEffect.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/profile/ProfileUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/CharacterSettingViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/IntroductionViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VoteHomeViewModel.kt
  feature/vote/src/main/res/values/strings.xml
Labels: 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥, 🔧리팩터링🔧
