Repository wespot-bff/WeSpot-Android, pull requests merged in 2024-09, with the labels that each got.

#152 #151 : 2차 배포 전 버그 수정
  app/src/main/kotlin/com/bff/wespot/CommonNavGraphNavigator.kt
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  core/model/src/main/kotlin/com/bff/wespot/model/notification/Notification.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/notification/NotificationDto.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/edit/ProfileEditScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteResultScreen.kt
  gradle/libs.versions.toml
Labels: 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟, 🧹허드렛일🧹

#156 #155 : 쪽지 QA 수정
  core/model/src/main/kotlin/com/bff/wespot/model/user/response/User.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/list/WSMessageItem.kt
  designsystem/src/main/res/drawable/closed_letter.png
  designsystem/src/main/res/drawable/opened_letter.png
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageStorageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/SendViewModel.kt
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#158 [FIX]#157: NameSpace 수정
  .github/workflows/opened-pr-notification.yml
  .github/workflows/submitted-pr-review-notification.yml
  app/.gitignore
  app/build.gradle.kts
  app/src/real/kotlin/com.bff.wespot/AnalyticsModule.kt
  app/src/real/kotlin/com.bff.wespot/FirebaseAnalyticsHelper.kt
Labels: 🍩브라우니🍩, 🌟머지 해주세요🌟

#164 #160 : 쪽지 코드 리팩토링해요
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/BaseMessage.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/BlockedMessage.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/Message.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/MessageList.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/ReceivedMessage.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/SentMessage.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/SentMessageList.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/response/BlockedMessageDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/response/MessageDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/response/MessageListDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/di/PagingModule.kt
  data/src/main/kotlin/com/bff/wespot/data/paging/message/MessageSentPagingSource.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/message/MessageRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/message/MessageSentPagingRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/message/MessageRepository.kt
  feature/entire/src/main/res/drawable/vote_question_ask.png
  feature/message/src/main/kotlin/com/bff/wespot/message/common/Constants.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/model/ClickedMessageUiModel.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageHomeScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/ReservedMessageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/MessageEditScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/storage/MessageStorageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageAction.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageSideEffect.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageUiState.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/storage/StorageAction.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/storage/StorageSideEffect.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/storage/StorageUiState.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/MessageViewModel.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/SendViewModel.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/StorageViewModel.kt
  feature/message/src/main/res/drawable/received_message.png
  feature/message/src/main/res/drawable/reserved_message.png
  feature/vote/src/main/res/drawable/vote_badge.png
Labels: 🍻제이콥🍻, 🔨픽스🔨, 🔥리뷰 기다리는 중🔥, 🔧리팩터링🔧

#166 #165: 3차 버그 수정
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  core/model/src/main/kotlin/com/bff/wespot/model/common/RestrictionArg.kt
  designsystem/src/main/res/drawable/high_school.png
  designsystem/src/main/res/drawable/hight_school.png
  designsystem/src/main/res/drawable/middle_school.png
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/SchoolScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageHomeScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/CharacterSettingScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteHomeScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteResultScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VotingScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/voting/VotingUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VotingViewModel.kt
  feature/vote/src/main/res/values/strings.xml
Labels: 🍩브라우니🍩, 🌟머지 해주세요🌟

#170 #169: 카카오톡 로그인 앱으로 안하는 이슈 수정
  core/ui/build.gradle.kts
  core/ui/src/main/kotlin/com/bff/wespot/util/KakaoLoginManager.kt
  data/build.gradle.kts
  data/src/main/kotlin/com/bff/wespot/data/di/DataModule.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/auth/KakaoLoginManager.kt
  domain/src/main/kotlin/com/bff/wespot/domain/usecase/KakaoLoginUseCase.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/AuthScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/state/AuthAction.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/viewmodel/AuthViewModel.kt
Labels: 🍩브라우니🍩, 🔨픽스🔨, ✏️수정 요청✏️

#167 #163 : 알림 이슈 수정
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  app/src/main/kotlin/com/bff/wespot/NavigatorImpl.kt
  app/src/main/kotlin/com/bff/wespot/NotificationNavigatorImpl.kt
  app/src/main/kotlin/com/bff/wespot/PushNotificationService.kt
  app/src/main/kotlin/com/bff/wespot/di/ConfigModule.kt
  app/src/main/kotlin/com/bff/wespot/splash/SplashActivity.kt
  app/src/main/kotlin/com/bff/wespot/splash/SplashViewModel.kt
  app/src/main/kotlin/com/bff/wespot/viewmodel/MainViewModel.kt
  core/model/src/main/kotlin/com/bff/wespot/model/notification/Notification.kt
  core/model/src/main/kotlin/com/bff/wespot/model/notification/NotificationType.kt
  core/navigation/src/main/kotlin/com/bff/wespot/navigation/Navigator.kt
  core/navigation/src/main/kotlin/com/bff/wespot/navigation/util/ExtraConstants.kt
  data-remote/build.gradle.kts
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/di/DataRemoteModule.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/firebase/config/RemoteConfigDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/firebase/config/RemoteConfigDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/firebase/messaging/MessagingDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/firebase/messaging/MessagingDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/di/ClientModule.kt
  data/src/main/kotlin/com/bff/wespot/data/di/DataModule.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/firebase/config/RemoteConfigRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/firebase/messaging/MessagingRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/user/UserRepositoryImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/firebase/config/RemoteConfigRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/firebase/messaging/MessagingRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/usecase/AutoLoginUseCase.kt
  domain/src/main/kotlin/com/bff/wespot/domain/usecase/KakaoLoginUseCase.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/AuthActivity.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/viewmodel/AuthViewModel.kt
  feature/entire/src/main/java/com/bff/wespot/entire/viewmodel/EntireEditViewModel.kt
  feature/entire/src/main/java/com/bff/wespot/entire/viewmodel/EntireViewModel.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/MessageViewModel.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/StorageViewModel.kt
  feature/notification/src/main/kotlin/com/bff/wespot/notification/screen/NotificationScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteResultScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/result/ResultUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VoteHomeViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VoteResultViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VotingViewModel.kt
Labels: 🍻제이콥🍻, 🔨픽스🔨
