Repository wespot-bff/WeSpot-Android, pull requests merged in 2024-08, with the labels that each got.

#67 #66, #55: 투표 보관함및 투표 화면 완성하기
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/CommonNavGraphNavigator.kt
  core/common/src/main/kotlin/com/bff/wespot/common/util/DateTimeConverter.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/IndividualReceived.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/IndividualSent.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/ReceivedVoteData.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/ReceivedVoteResult.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/SentVoteData.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/SentVoteResult.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/StorageVoteResult.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/VoteData.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/VoteReceived.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/VoteSent.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/ListBottomGradient.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/MultiLineText.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/RedDot.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/WSCarousel.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/di/ClientModule.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/IndividualReceivedDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/IndividualSentDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/ReceivedVoteDataDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/ReceivedVoteResultDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/SentVoteDataDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/SentVoteResultDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/VoteReceivedDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/VoteSentDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/vote/VoteDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/vote/VoteDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/auth/AuthRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/vote/VoteRepositoryImpl.kt
  designsystem/src/main/res/drawable/white_logo.png
  domain/src/main/kotlin/com/bff/wespot/domain/repository/vote/VoteRepository.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/IndividualVoteScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteHomeScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteResultScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteStorageScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VotingScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/storage/StorageAction.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/storage/StorageSideEffect.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/storage/StorageUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/ui/VoteCard.kt
  feature/vote/src/main/java/com/bff/wespot/vote/ui/VoteChip.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/IndividualViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VoteStorageViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VotingViewModel.kt
  feature/vote/src/main/res/drawable/guide_image.png
  feature/vote/src/main/res/drawable/no_vote.png
  feature/vote/src/main/res/drawable/vote_badge.png
  feature/vote/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#70 #65 : 전체 탭 설정 화면 구현
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/CommonNavGraphNavigator.kt
  core/model/src/main/kotlin/com/bff/wespot/model/user/response/Profile.kt
  core/model/src/main/kotlin/com/bff/wespot/model/user/response/User.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/banner/WSBanner.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/modal/WSDialog.kt
  feature/entire/build.gradle.kts
  feature/entire/src/main/java/com/bff/wespot/entire/screen/EntireScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/component/EntireListItem.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/AccountSettingScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/EntireScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/NotificationSettingScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/SettingScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/state/EntireAction.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/state/EntireSideEffect.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/state/EntireUiState.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/viewmodel/EntireViewModel.kt
  feature/entire/src/main/res/drawable/setting.xml
  feature/entire/src/main/res/drawable/vote_question_ask.png
  feature/entire/src/main/res/values/strings.xml
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/ReservedMessageScreen.kt
  feature/message/src/main/res/values/strings.xml
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteStorageScreen.kt
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥

#73 #64 : 회원 탈퇴 기능 구현
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/CommonNavGraphNavigator.kt
  app/src/main/kotlin/com/bff/wespot/NavigatorImpl.kt
  core/model/src/main/kotlin/com/bff/wespot/model/auth/request/RevokeReasonListDto.kt
  core/navigation/src/main/kotlin/com/bff/wespot/navigation/Navigator.kt
  core/navigation/src/main/kotlin/com/bff/wespot/navigation/util/ExtraConstants.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/auth/AuthDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/auth/AuthDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/auth/AuthRepositoryImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/auth/AuthRepository.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/AuthActivity.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/AccountSettingScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/revoke/RevokeConfirmScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/revoke/RevokeScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/state/EntireAction.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/state/EntireSideEffect.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/state/EntireUiState.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/viewmodel/EntireViewModel.kt
  feature/entire/src/main/res/drawable/ic_check.xml
  feature/entire/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#72 #68: 짜잘한 기능들을 추가해요
  core/model/src/main/kotlin/com/bff/wespot/model/ReportType.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/IndividualReceived.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/IndividualSent.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/Profile.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/SentVoteResult.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/VoteResults.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/VoteUser.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/ReportBottomSheet.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/di/ClientModule.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/di/DataRemoteModule.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/MessageContentDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/ReportDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/request/MessageContentDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/IndividualReceivedDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/IndividualSentDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/SentVoteResultDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/VoteResultsDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/VoteUserDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/CommonDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/CommonDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/auth/AuthDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/vote/VoteDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/di/DataModule.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/CommonRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/message/MessageRepositoryImpl.kt
  designsystem/src/main/res/values/strings.xml
  domain/src/main/kotlin/com/bff/wespot/domain/repository/CommonRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/message/MessageRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/usecase/CheckProfanityUseCase.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/AuthActivity.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/NameScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/state/AuthAction.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/state/AuthUiState.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/viewmodel/AuthViewModel.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/MessageWriteScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/SendViewModel.kt
  feature/message/src/main/res/values/strings.xml
  feature/vote/src/main/java/com/bff/wespot/vote/screen/IndividualVoteScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteHomeScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteResultScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VotingScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/voting/VotingAction.kt
  feature/vote/src/main/java/com/bff/wespot/vote/ui/VoteCard.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/IndividualViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VotingViewModel.kt
  feature/vote/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥

#77 #69: 회원가입후 5초뒤 프로필 설정 추가
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/CommonNavGraphNavigator.kt
  core/model/src/main/kotlin/com/bff/wespot/model/common/BackgroundColor.kt
  core/model/src/main/kotlin/com/bff/wespot/model/common/Character.kt
  core/model/src/main/kotlin/com/bff/wespot/model/common/ReportType.kt
  core/ui/build.gradle.kts
  core/ui/src/main/kotlin/com/bff/wespot/ui/CharacterScreen.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/IntroductionScreen.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/MultiLineText.kt
  core/ui/src/main/res/drawable/background.png
  core/ui/src/main/res/drawable/character.png
  core/ui/src/main/res/values/strings.xml
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/common/BackgroundColorDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/common/CharacterDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/common/EditProfileDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/common/ProfanityDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/common/ReportDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/CommonDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/CommonDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/CommonRepositoryImpl.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/header/WSTopBar.kt
  designsystem/src/main/res/values/strings.xml
  domain/src/main/kotlin/com/bff/wespot/domain/repository/CommonRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/util/DataStoreKey.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/CharacterSettingScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/IntroductionScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteHomeScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VotingScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/home/VoteAction.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/home/VoteUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/profile/ProfileAction.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/profile/ProfileSideEffect.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/profile/ProfileUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/CharacterSettingViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/IntroductionViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VoteHomeViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VotingViewModel.kt
  feature/vote/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#79 #74 : 차단된 메세지 리스트업 및 차단 해제 구현
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/CommonNavGraphNavigator.kt
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/Sender.kt
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/BlockedMessage.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/IntroductionScreen.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/ReservedMessageItem.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/WSListItem.kt
  core/ui/src/main/res/values/string.xml
  core/ui/src/main/res/values/strings.xml
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/response/BlockedMessageDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/response/SenderDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/message/MessageRepositoryImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/message/MessageRepository.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/AccountSettingScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/BlockListScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/EntireScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/SettingScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/revoke/RevokeConfirmScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/state/EntireAction.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/state/EntireSideEffect.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/state/EntireUiState.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/viewmodel/EntireViewModel.kt
  feature/entire/src/main/res/drawable/ic_setting.xml
  feature/entire/src/main/res/values/strings.xml
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/ReservedMessageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/MessageEditScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/MessageWriteScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/ReceiverSelectionScreen.kt
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#81 #71: 공유 기능 추가해요
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  app/src/main/kotlin/com/bff/wespot/NavigatorImpl.kt
  app/src/main/res/xml/provider_paths.xml
  build-logic/convention/src/main/kotlin/com/bff/wespot/plugin/AndroidApplicationPlugin.kt
  core/common/build.gradle.kts
  core/common/src/main/kotlin/com/bff/wespot/common/extension/onNetworkFailure.kt
  core/common/src/main/kotlin/com/bff/wespot/common/util/DateTimeConverter.kt
  core/common/src/main/kotlin/com/bff/wespot/common/util/RandomNameGenerator.kt
  core/navigation/src/main/kotlin/com/bff/wespot/navigation/Navigator.kt
  core/ui/build.gradle.kts
  core/ui/src/main/kotlin/com/bff/wespot/ui/CaptureBitmap.kt
  core/ui/src/main/kotlin/com/bff/wespot/util/CoroutineModule.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/MessageContentDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/auth/AuthDataSourceImpl.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/banner/WSBanner.kt
  domain/src/main/kotlin/com/bff/wespot/domain/util/DataStoreKey.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/AuthActivity.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/CompleteScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/SendViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/IndividualVoteScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteHomeScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteResultScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/result/ResultAction.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/result/ResultUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VoteHomeViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VoteResultViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VotingViewModel.kt
Labels: 🌱기능🌱, 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥

#85 #83: TextField 문제 수정해요
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/input/WsTextField.kt
Labels: 🍩브라우니🍩, 🔨픽스🔨, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#80 #75 : 알림 탭 화면 구현
  app/build.gradle.kts
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/CommonNavGraphNavigator.kt
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  app/src/main/kotlin/com/bff/wespot/PushNotificationService.kt
  core/common/src/main/kotlin/com/bff/wespot/common/util/DateTimeConverter.kt
  core/model/src/main/kotlin/com/bff/wespot/model/notification/Notification.kt
  core/model/src/main/kotlin/com/bff/wespot/model/notification/NotificationType.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/RedDot.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/di/DataRemoteModule.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/extensions/DateTimeExtensions.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/notification/NotificationDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageStorageDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageStorageDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/notification/NotificationDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/notification/NotificationDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/di/DataModule.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/message/MessageStorageRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/notification/NotificationRepositoryImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/message/MessageStorageRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/notification/NotificationRepository.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/NotificationSettingScreen.kt
  feature/entire/src/main/res/values/strings.xml
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/MessageViewModel.kt
  feature/notification/.gitignore
  feature/notification/build.gradle.kts
  feature/notification/consumer-rules.pro
  feature/notification/proguard-rules.pro
  feature/notification/src/main/kotlin/com/bff/wespot/notification/screen/NotificationScreen.kt
  feature/notification/src/main/kotlin/com/bff/wespot/notification/state/NotificationAction.kt
  feature/notification/src/main/kotlin/com/bff/wespot/notification/state/NotificationSideEffect.kt
  feature/notification/src/main/kotlin/com/bff/wespot/notification/state/NotificationUiState.kt
  feature/notification/src/main/kotlin/com/bff/wespot/notification/viewmodel/NotificationViewModel.kt
  feature/notification/src/main/res/drawable/ic_notification.xml
  feature/notification/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥

#82 #61 : 프로필 수정 구현
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/CommonNavGraphNavigator.kt
  core/ui/src/main/kotlin/com/bff/wespot/model/ToastState.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/CharacterScreen.kt
  core/ui/src/main/res/values/strings.xml
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/user/request/IntroductionDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/user/UserDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/user/UserDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/mapper/user/UserMapper.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/user/UserRepositoryImpl.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/input/WsTextField.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/user/UserRepository.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/common/constants.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/EntireScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/edit/CharacterEditScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/edit/ProfileEditScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/setting/AccountSettingScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/setting/BlockListScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/setting/NotificationSettingScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/setting/RevokeConfirmScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/setting/RevokeScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/screen/setting/SettingScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/state/edit/EntireEditAction.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/state/edit/EntireEditSideEffect.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/state/edit/EntireEditUiState.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/viewmodel/EntireEditViewModel.kt
  feature/entire/src/main/res/drawable/edit.png
  feature/entire/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#88 #78: refresh token 로직추가및 리얼 서버 연결
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  app/src/main/kotlin/com/bff/wespot/NavigatorImpl.kt
  core/common/src/main/kotlin/com/bff/wespot/common/util/DateTimeConverter.kt
  core/model/src/main/kotlin/com/bff/wespot/model/auth/request/KakaoAuthToken.kt
  data-local/src/main/java/com/bff/wespot/data/local/source/WeSpotDataStore.kt
  data-local/src/main/java/com/bff/wespot/data/local/source/WeSpotDataStoreImpl.kt
  data-remote/build.gradle.kts
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/di/ClientModule.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/extensions/HttpClientExtension.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/common/TokenDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/request/VoteResultsUploadDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/VoteResultsDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/auth/AuthDataSourceImpl.kt
  data/build.gradle.kts
  data/src/main/kotlin/com/bff/wespot/data/di/ClientModule.kt
  data/src/main/kotlin/com/bff/wespot/data/mapper/auth/AuthMapper.kt
  data/src/main/kotlin/com/bff/wespot/data/mapper/vote/VoteMapper.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/DataStoreRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/auth/AuthRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/auth/KakaoLoginManagerImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/DataStoreRepository.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/EditScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/NameScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VotingViewModel.kt
Labels: 🌱기능🌱, 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥, 🧹허드렛일🧹

#89 #63 : 알림 설정 기능 구현
  core/model/src/main/kotlin/com/bff/wespot/model/user/response/NotificationSetting.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/user/response/NotificationSettingDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/user/UserDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/user/UserDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/mapper/user/UserMapper.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/user/UserRepositoryImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/user/UserRepository.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/setting/NotificationSettingScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/setting/SettingScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/state/notification/NotificationSettingAction.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/state/notification/NotificationSettingSideEffect.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/state/notification/NotificationSettingUiState.kt
  feature/entire/src/main/java/com/bff/wespot/entire/viewmodel/NotificationSettingViewModel.kt
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥

#98 #87: 이미지 수정 및 로띠 추가
  app/src/main/kotlin/com/bff/wespot/BottomBarDestinations.kt
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/DotIndicators.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/banner/WSBanner.kt
  designsystem/src/main/res/drawable/entire.xml
  designsystem/src/main/res/drawable/entire_empty.xml
  designsystem/src/main/res/drawable/entire_tab.xml
  designsystem/src/main/res/drawable/hight_school.png
  designsystem/src/main/res/drawable/message.xml
  designsystem/src/main/res/drawable/message_empty.xml
  designsystem/src/main/res/drawable/message_tab.xml
  designsystem/src/main/res/drawable/middle_school.png
  designsystem/src/main/res/drawable/vote_empty.xml
  feature/auth/build.gradle.kts
  feature/auth/src/main/kotlin/com/bff/wespot/auth/AuthActivity.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/AuthScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/CompleteScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/SchoolScreen.kt
  feature/auth/src/main/res/drawable/onboarding_01_bkg.png
  feature/auth/src/main/res/drawable/onboarding_02_bkg.png
  feature/auth/src/main/res/drawable/onboarding_03_bkg.png
  feature/auth/src/main/res/drawable/register_complete.png
  feature/auth/src/main/res/raw/onboarding01.json
  feature/auth/src/main/res/raw/onboarding03.json
  feature/auth/src/main/res/values/strings.xml
  feature/vote/build.gradle.kts
  feature/vote/src/main/java/com/bff/wespot/vote/screen/CharacterSettingScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteHomeScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteResultScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteStorageScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VotingScreen.kt
  feature/vote/src/main/res/drawable/vote_gradient.png
  feature/vote/src/main/res/raw/vote_find.json
  feature/vote/src/main/res/raw/vote_home.json
  feature/vote/src/main/res/raw/vote_swipe.json
  feature/vote/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🍩브라우니🍩

#99 #86: Paging 기능 추가
  core/common/src/main/kotlin/com/bff/wespot/common/util/DateTimeConverter.kt
  core/model/src/main/kotlin/com/bff/wespot/model/common/Paging.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/VoteReceived.kt
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/VoteSent.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/request/VoteResultsUploadDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/VoteReceivedDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/VoteResultsDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/VoteSentDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/vote/VoteDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/vote/VoteDataSourceImpl.kt
  data/build.gradle.kts
  data/src/main/kotlin/com/bff/wespot/data/di/PagingModule.kt
  data/src/main/kotlin/com/bff/wespot/data/mapper/vote/VoteMapper.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/vote/VoteReceivedPagingRepository.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/vote/VoteReceivedPagingSource.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/vote/VoteRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/vote/VoteSentPagingRepository.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/vote/VoteSentPagingSource.kt
  domain/build.gradle.kts
  domain/src/main/kotlin/com/bff/wespot/domain/paging/BasePagingSource.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/BasePagingRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/vote/VoteRepository.kt
  feature/vote/build.gradle.kts
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteStorageScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/storage/StorageUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VoteStorageViewModel.kt
  gradle/libs.versions.toml
Labels: 🌱기능🌱, 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥

#103 #94: 문제가 있는 로직 수정
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/bff/wespot/PushNotificationService.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/auth/request/KakaoAuthTokenDto.kt
  data/src/main/kotlin/com/bff/wespot/data/mapper/auth/AuthMapper.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/auth/AuthRepositoryImpl.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/EditScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/GenderScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/GradeScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/NameScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteResultScreen.kt
  feature/vote/src/main/res/drawable/blur_2.png
  feature/vote/src/main/res/drawable/blur_3.png
  feature/vote/src/main/res/drawable/blur_4.png
  feature/vote/src/main/res/drawable/blur_5.png
  feature/vote/src/main/res/drawable/logo1.png
  feature/vote/src/main/res/drawable/logo2.png
  feature/vote/src/main/res/drawable/logo3.png
  gradle/libs.versions.toml
Labels: 🌱기능🌱, 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#102 #101: Firebase Analytics로 로깅하기
  app/build.gradle.kts
  app/src/dev/kotlin/com/bff/wespot/AnalyticsModule.kt
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  app/src/prod/kotlin/com.bff.wespot/AnalyticsModule.kt
  app/src/prod/kotlin/com.bff.wespot/FirebaseAnalyticsHelper.kt
  core/analytics/.gitignore
  core/analytics/build.gradle.kts
  core/analytics/consumer-rules.pro
  core/analytics/proguard-rules.pro
  core/analytics/src/main/AndroidManifest.xml
  core/analytics/src/main/java/com/bff/wespot/analytic/AnalyticExtension.kt
  core/analytics/src/main/java/com/bff/wespot/analytic/AnalyticsEvent.kt
  core/analytics/src/main/java/com/bff/wespot/analytic/AnalyticsHelper.kt
  core/analytics/src/main/java/com/bff/wespot/analytic/DebugAnalyicsHelper.kt
  core/analytics/src/main/java/com/bff/wespot/analytic/NoOpAnalyticsHelper.kt
  feature/vote/build.gradle.kts
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteHomeScreen.kt
  settings.gradle.kts
Labels: 🌱기능🌱, 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥

#104 #100: 카카오톡 공유 기능 추가
  app/build.gradle.kts
  app/src/main/kotlin/com/bff/wespot/NavigatorImpl.kt
  core/navigation/src/main/kotlin/com/bff/wespot/navigation/Navigator.kt
  gradle/libs.versions.toml
Labels: 🌱기능🌱, 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#106 #96: Firebase remote config를 추가해요
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/bff/wespot/di/ConfigModule.kt
  app/src/main/kotlin/com/bff/wespot/splash/SplashActivity.kt
  app/src/main/kotlin/com/bff/wespot/splash/SplashViewModel.kt
  app/src/main/res/xml/remote_default_config.xml
  data-remote/build.gradle.kts
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/config/RemoteConfigDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/config/RemoteConfigDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/di/DataRemoteModule.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/CommonDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/auth/AuthDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageStorageDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/notification/NotificationDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/user/UserDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/vote/VoteDataSourceImpl.kt
  data/build.gradle.kts
  data/src/main/kotlin/com/bff/wespot/data/di/ClientModule.kt
  data/src/main/kotlin/com/bff/wespot/data/di/DataModule.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/RemoteConfigRepositoryImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/RemoteConfigRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/util/RemoteConfigKey.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/AuthActivity.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/viewmodel/AuthViewModel.kt
  gradle/libs.versions.toml
Labels: 🌱기능🌱, 🍩브라우니🍩, 🌟머지 해주세요🌟

#112 #105: 짜잘한 기능 추가
  core/model/src/main/kotlin/com/bff/wespot/model/auth/response/SchoolList.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/auth/response/SchoolListDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/auth/AuthDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/auth/AuthDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/di/PagingModule.kt
  data/src/main/kotlin/com/bff/wespot/data/paging/auth/SchoolPagingSource.kt
  data/src/main/kotlin/com/bff/wespot/data/paging/vote/VoteReceivedPagingSource.kt
  data/src/main/kotlin/com/bff/wespot/data/paging/vote/VoteSentPagingSource.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/auth/AuthRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/auth/SchoolPagingRepository.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/vote/VoteReceivedPagingRepository.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/vote/VoteSentPagingRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/BasePagingRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/auth/AuthRepository.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/NameScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/SchoolScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/state/AuthUiState.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/viewmodel/AuthViewModel.kt
  feature/entire/src/main/java/com/bff/wespot/entire/viewmodel/EntireViewModel.kt
Labels: 🌱기능🌱, 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#107 #97, #93 : 쪽지 본서버 연동 및 프로필 데이터 캐싱
  app/.gitignore
  app/build.gradle.kts
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  app/src/main/kotlin/com/bff/wespot/state/MainAction.kt
  app/src/main/kotlin/com/bff/wespot/state/MainSideEffect.kt
  app/src/main/kotlin/com/bff/wespot/state/MainUiState.kt
  app/src/main/kotlin/com/bff/wespot/viewmodel/MainViewModel.kt
  app/src/main/res/values/strings.xml
  core/model/src/main/kotlin/com/bff/wespot/model/message/request/SentMessage.kt
  core/model/src/main/kotlin/com/bff/wespot/model/user/response/Profile.kt
  data-local/build.gradle.kts
  data-local/src/main/java/com/bff/wespot/data/local/common/mapper/ProfileMapper.kt
  data-local/src/main/java/com/bff/wespot/data/local/common/serializer/ProfileSerializer.kt
  data-local/src/main/java/com/bff/wespot/data/local/di/DataLocalModule.kt
  data-local/src/main/java/com/bff/wespot/data/local/di/ProtoDataStoreModule.kt
  data-local/src/main/java/com/bff/wespot/data/local/source/ProfileDataSource.kt
  data-local/src/main/java/com/bff/wespot/data/local/source/ProfileDataSourceImpl.kt
  data-local/src/main/proto/profile_preference.proto
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/request/SentMessageDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/CommonDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/notification/NotificationDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/di/DataModule.kt
  data/src/main/kotlin/com/bff/wespot/data/mapper/message/MessageMapper.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/user/ProfileRepositoryImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/user/ProfileRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/usecase/CacheProfileUseCase.kt
  domain/src/main/kotlin/com/bff/wespot/domain/usecase/UpdateProfileCharacterUseCase.kt
  domain/src/main/kotlin/com/bff/wespot/domain/usecase/UpdateProfileIntroductionUseCase.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/edit/ProfileEditScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/viewmodel/EntireEditViewModel.kt
  feature/entire/src/main/java/com/bff/wespot/entire/viewmodel/EntireViewModel.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageHomeScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/SendViewModel.kt
  gradle/libs.versions.toml
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#113 #110: 아이콘 및 Splash 수정
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/kotlin/com/bff/wespot/PushNotificationService.kt
  app/src/main/kotlin/com/bff/wespot/splash/SplashActivity.kt
  app/src/main/kotlin/com/bff/wespot/splash/SplashViewModel.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/icon.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/themes.xml
Labels: 🌱기능🌱, 🍩브라우니🍩, 🌟머지 해주세요🌟

#114 #111: QA에서 받은 내용 수정
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  app/src/main/kotlin/com/bff/wespot/NavigatorImpl.kt
  core/navigation/src/main/kotlin/com/bff/wespot/navigation/Navigator.kt
  core/ui/src/main/kotlin/com/bff/wespot/model/ToastState.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/CaptureBitmap.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/ListBottomGradient.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/TopToast.kt
  core/ui/src/main/kotlin/com/bff/wespot/util/ModifierUtil.kt
  core/ui/src/main/kotlin/com/bff/wespot/util/MultiClickCutter.kt
  core/ui/src/main/res/raw/loading.json
  data/src/main/kotlin/com/bff/wespot/data/di/DataModule.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/indicator/WSHomeTabRow.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/input/WsTextField.kt
  designsystem/src/main/res/drawable/icn_alarm.xml
  designsystem/src/main/res/drawable/icn_settings.xml
  designsystem/src/main/res/drawable/logo.png
  designsystem/src/main/res/drawable/main_logo.xml
  designsystem/src/main/res/drawable/question.png
  designsystem/src/main/res/values/strings.xml
  feature/auth/src/main/kotlin/com/bff/wespot/auth/AuthActivity.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/AuthScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/CompleteScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/EditScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/GenderScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/GradeScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/NameScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/SchoolScreen.kt
  feature/auth/src/main/res/values/string.xml
  feature/auth/src/main/res/values/strings.xml
  feature/entire/src/main/java/com/bff/wespot/entire/component/EntireListItem.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/EntireScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/edit/ProfileEditScreen.kt
  feature/entire/src/main/res/drawable/ic_setting.xml
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/ReservedMessageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/MessageEditScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/IndividualVoteScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteHomeScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteResultScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VotingScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/ui/VoteCard.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VoteResultViewModel.kt
  feature/vote/src/main/res/drawable/blur_4.png
  feature/vote/src/main/res/drawable/no_friends.png
  feature/vote/src/main/res/drawable/vote_background.png
  feature/vote/src/main/res/values/strings.xml
Labels: 🍩브라우니🍩, 🔨픽스🔨, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#125 #119: 회원가입, 투표 로그 추가
  app/src/dev/kotlin/com/bff/wespot/AnalyticsModule.kt
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  app/src/main/kotlin/com/bff/wespot/state/MainUiState.kt
  app/src/main/kotlin/com/bff/wespot/viewmodel/MainViewModel.kt
  app/src/prod/kotlin/com.bff.wespot/FirebaseAnalyticsHelper.kt
  core/analytics/src/main/java/com/bff/wespot/analytic/AnalyticExtension.kt
  core/analytics/src/main/java/com/bff/wespot/analytic/AnalyticsHelper.kt
  core/analytics/src/main/java/com/bff/wespot/analytic/DebugAnalyicsHelper.kt
  core/analytics/src/main/java/com/bff/wespot/analytic/NoOpAnalyticsHelper.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/user/UserRepositoryImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/util/DataStoreKey.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/kotlin/com/bff/wespot/auth/AuthActivity.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/AuthScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/ClassScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/CompleteScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/EditScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/GenderScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/GradeScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/NameScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/SchoolScreen.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/state/AuthUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/CharacterSettingScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/IndividualVoteScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/IntroductionScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VotingScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/profile/ProfileUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/state/voting/VotingUiState.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/CharacterSettingViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/IntroductionViewModel.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/VotingViewModel.kt
  feature/vote/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#124 #122 : 회원탈퇴 UI 변경 및 알림탭/푸시 클릭시 화면 전환
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/CommonNavGraphNavigator.kt
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  app/src/main/kotlin/com/bff/wespot/NotificationNavigatorImpl.kt
  app/src/main/kotlin/com/bff/wespot/PushNotificationService.kt
  app/src/main/kotlin/com/bff/wespot/state/MainAction.kt
  app/src/main/kotlin/com/bff/wespot/state/MainUiState.kt
  app/src/main/kotlin/com/bff/wespot/viewmodel/MainViewModel.kt
  app/src/main/res/mipmap-anydpi-v26/ic_notification.png
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/MessageStatus.kt
  core/model/src/main/kotlin/com/bff/wespot/model/notification/NotificationType.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/common/ReportDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/response/MessageStatusDto.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/CommonRepositoryImpl.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/setting/RevokeConfirmScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/setting/RevokeScreen.kt
  feature/entire/src/main/res/drawable/revoke_character.png
  feature/message/src/main/kotlin/com/bff/wespot/message/component/ReservedMessageBanner.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageHomeScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageStorageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/ReceiverSelectionScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/MessageUiState.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/state/send/SendUiState.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/viewmodel/SendViewModel.kt
  feature/notification/src/main/kotlin/com/bff/wespot/notification/screen/NotificationScreen.kt
  feature/notification/src/main/kotlin/com/bff/wespot/notification/state/NotificationUiState.kt
  feature/notification/src/main/kotlin/com/bff/wespot/notification/viewmodel/NotificationViewModel.kt
  feature/notification/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🍻제이콥🍻, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#132 #127: 문제 있는 부분을 수정해요
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  app/src/main/kotlin/com/bff/wespot/BarType.kt
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/AutoSizeText.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/CharacterScreen.kt
  core/ui/src/main/res/drawable/background.png
  core/ui/src/main/res/drawable/background.xml
  core/ui/src/main/res/drawable/character.png
  core/ui/src/main/res/drawable/character.xml
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/indicator/WSHomeTabRow.kt
  designsystem/src/main/res/drawable/entire_tab.xml
  designsystem/src/main/res/drawable/icn_alarm.xml
  designsystem/src/main/res/values/strings.xml
  domain/src/main/kotlin/com/bff/wespot/domain/paging/BasePagingSource.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/EntireScreen.kt
  feature/entire/src/main/res/values/strings.xml
  feature/message/src/main/res/values/strings.xml
  feature/notification/src/main/kotlin/com/bff/wespot/notification/screen/NotificationScreen.kt
  feature/notification/src/main/res/values/strings.xml
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteStorageScreen.kt
  feature/vote/src/main/res/raw/vote_home.json
  feature/vote/src/main/res/values/strings.xml
Labels: 🍩브라우니🍩, 🔨픽스🔨, 🌟머지 해주세요🌟

#135 #128, #130 : 프로필 수정화면 수정 및 푸시 알림 버그 수정
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/ReservedMessageItem.kt
  designsystem/src/main/kotlin/com/bff/wespot/designsystem/component/banner/WSBanner.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/EntireScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/edit/ProfileEditScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/screen/setting/NotificationSettingScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageStorageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/MessageEditScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/MessageWriteScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/ReceiverSelectionScreen.kt
  feature/message/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🍻제이콥🍻, 🌟머지 해주세요🌟

#136 #134: 투표 인터렉션 추가
  app/src/main/kotlin/com/bff/wespot/AppNavGraphs.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VotingScreen.kt
Labels: 🌱기능🌱, 🍩브라우니🍩, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟

#142 #141: 문제 수정 3트
  core/ui/src/main/kotlin/com/bff/wespot/ui/WSListItem.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteStorageScreen.kt
  feature/vote/src/main/res/values/strings.xml
Labels: 🍩브라우니🍩, 🔨픽스🔨, 🌟머지 해주세요🌟

#144 #138: 로그인후 이용제한 확인하기
  app/src/main/kotlin/com/bff/wespot/MainActivity.kt
  app/src/main/kotlin/com/bff/wespot/state/MainUiState.kt
  app/src/main/kotlin/com/bff/wespot/viewmodel/MainViewModel.kt
  app/src/main/res/values/strings.xml
  core/model/src/main/kotlin/com/bff/wespot/model/common/Restriction.kt
  core/model/src/main/kotlin/com/bff/wespot/model/common/RestrictionType.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/common/RestrictionDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/CommonDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/CommonDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/CommonRepositoryImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/CommonRepository.kt
  feature/auth/src/main/kotlin/com/bff/wespot/auth/screen/SchoolScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteHomeScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteResultScreen.kt
Labels: 🌱기능🌱, 🍩브라우니🍩, 🌟머지 해주세요🌟

#146 #145: 개별 투표 결과 화면 코드 정리해용
  core/model/src/main/kotlin/com/bff/wespot/model/vote/response/IndividualSent.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/vote/response/IndividualSentDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/vote/VoteDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/vote/VoteDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/vote/VoteRepositoryImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/vote/VoteRepository.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/IndividualVoteScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteResultScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/screen/VoteStorageScreen.kt
  feature/vote/src/main/java/com/bff/wespot/vote/ui/VoteCard.kt
  feature/vote/src/main/java/com/bff/wespot/vote/viewmodel/IndividualViewModel.kt
Labels: 🍩브라우니🍩, 🔨픽스🔨, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟, 🔧리팩터링🔧

#148 #147: 모바일 데이터 전환시 체크 안되는 문제 수정
  app/src/main/AndroidManifest.xml
  core/ui/src/main/kotlin/com/bff/wespot/network/NetworkStateChecker.kt
  core/ui/src/main/kotlin/com/bff/wespot/ui/TopToast.kt
Labels: 🍩브라우니🍩, 🔨픽스🔨

#150 #149 : 페이징 이슈 및 버그 수정
  build-logic/convention/src/main/kotlin/com/bff/wespot/plugin/AndroidApplicationFirebasePlugin.kt
  build.gradle.kts
  core/model/src/main/kotlin/com/bff/wespot/model/message/response/BlockedMessageList.kt
  core/model/src/main/kotlin/com/bff/wespot/model/notification/Notification.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/message/response/BlockedMessageDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/model/notification/NotificationDto.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageDataSourceImpl.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageStorageDataSource.kt
  data-remote/src/main/kotlin/com/bff/wespot/data/remote/source/message/MessageStorageDataSourceImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/di/PagingModule.kt
  data/src/main/kotlin/com/bff/wespot/data/paging/message/MessageBlockedPagingSource.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/message/MessageBlockedPagingRepository.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/message/MessageRepositoryImpl.kt
  data/src/main/kotlin/com/bff/wespot/data/repository/message/MessageStorageRepositoryImpl.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/message/MessageRepository.kt
  domain/src/main/kotlin/com/bff/wespot/domain/repository/message/MessageStorageRepository.kt
  feature/entire/build.gradle.kts
  feature/entire/src/main/java/com/bff/wespot/entire/screen/setting/BlockListScreen.kt
  feature/entire/src/main/java/com/bff/wespot/entire/state/EntireUiState.kt
  feature/entire/src/main/java/com/bff/wespot/entire/viewmodel/EntireViewModel.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/MessageStorageScreen.kt
  feature/message/src/main/kotlin/com/bff/wespot/message/screen/send/ReceiverSelectionScreen.kt
  feature/notification/src/main/kotlin/com/bff/wespot/notification/screen/NotificationScreen.kt
  gradle/libs.versions.toml
Labels: 🌱기능🌱, 🍻제이콥🍻, 🌟머지 해주세요🌟
